name: Hello World! 

on:
  workflow_dispatch: # by hand start

# on:
#   push:
#     branches:
#       - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - run: echo "Hallo ohne eigenem benannten step"
