# This is a basic workflow to help you get started with Actions

name: Outputs-mit-Sophie-20.01

# Controls when the workflow will run


on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
    #Ziel vom outputs: outputs von Job 1 zu job 2 zu uebergeben
    job1:
        runs-on: ubuntu-latest
        # github action bennenung
        steps:
            - uses: actions/checkout@v4

            - name: job 1 step 1
              run: echo "Hallo from Job 1"






    job2:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: job 2 step 1
              run: echo "Hallo from Job 1"